version: '3'

services:
  ml-api:
    build: .
    environment:
      - PORT=8000
    platform: linux/x86_64
    ports:
      - '8000:8000'
    volumes:
      - '.:/ml-api'
    tty: true
    stdin_open: true
