version: 2.1

defaults: &defaults
  docker:
    - image: cimg/python:3.9.9
  working_directory: ~/project

jobs:
  build:
    <<: *defaults
    steps:
      - checkout:
          path: ~/project
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev_requirements.txt
  test:
    <<: *defaults
    steps:
      - run:
          name: run testing
          command: |
            pytest tests

workflows:
  version: 2
  test:
    jobs:
      - build
      - test:
          requires:
            - build
